### PR TITLE
Fix for https://github.com/eclipse/che/issues/2284

### PR DESCRIPTION
**Pull request by benoitf**
on native we can use docker0

Change-Id: If44ddd1a1cee1a17f41a7a3ce3354368c9275ff9
Signed-off-by: Florent BENOIT <fbenoit@codenvy.com>

### CODE REVIEW

**Comment by TylerJewell** [comment]
+1 lgtm - ok to merge.

**Comment by dmytro-ndp** [comment]
@benoitf: could you, please say if it is correct that _ifconfig_ on **che-ip** doesn't return **docker0** interface:
```
docker run -ti codenvy/che-ip:nightly "ifconfig"
> eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:01  
>           inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
>           inet6 addr: fe80::42:acff:fe11:1%32630/64 Scope:Link
>           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>           RX packets:1 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:1 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:0 
>           RX bytes:90 (90.0 B)  TX bytes:90 (90.0 B)
> 
> lo        Link encap:Local Loopback  
>           inet addr:127.0.0.1  Mask:255.0.0.0
>           inet6 addr: ::1%32630/128 Scope:Host
>           UP LOOPBACK RUNNING  MTU:65536  Metric:1
>           RX packets:0 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:0 
>           RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

```

**Comment by TylerJewell** [comment]
He is on holiday for a week.

**Comment by dmytro-ndp** [comment]
I see.
It seems, I sorted it out myself:
```[root@dev vagrant]#  docker run --net host --rm codenvy/che-ip:nightly ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:00:9C:9F:F2  
          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:ff:fe9c:9ff2%32655/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:12765 errors:0 dropped:0 overruns:0 frame:0
          TX packets:14998 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:532487 (520.0 KiB)  TX bytes:45885981 (43.7 MiB)

eth0      Link encap:Ethernet  HWaddr 08:00:27:7D:D3:BF  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe7d:d3bf%32655/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:763708 errors:0 dropped:0 overruns:0 frame:0
          TX packets:223647 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:780138954 (743.9 MiB)  TX bytes:15506706 (14.7 MiB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:5C:EA:50  
          inet addr:192.168.56.110  Bcast:192.168.56.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe5c:ea50%32655/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3772 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6575 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:642031 (626.9 KiB)  TX bytes:10363128 (9.8 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1%32655/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:262831 errors:0 dropped:0 overruns:0 frame:0
          TX packets:262831 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:244284747 (232.9 MiB)  TX bytes:244284747 (232.9 MiB)```

**Comment by benoitf** [comment]
Yes @dmytro-np you figured out that when we call che-ip we've to provide --net host parameter

**Pull request merged**
