### PR TITLE
Add Angular and Sails support

### PR DESCRIPTION
**Pull request by monaka**
### What does this PR do?

Adding images for Angular (a.k.a Angular2) and Sails (Ruby on Rails like framework for Node).

### What issues does this PR fix or reference?

No.

### New behavior

More images available.

### Tests written?

No

### Docs updated?

No

### CODE REVIEW

**Comment by TylerJewell** [comment]
@eivantsov - given the additional policies for package management, is this type of stack meeting those requirements?

**Comment by eivantsov** [comment]
I'd rather add those npms to https://github.com/eclipse/che-dockerfiles/blob/master/recipes/node/Dockerfile

**Comment by monaka** [comment]
I think it's better to keep the base node image simple.
Because sometimes it will causes a version hell by adding many npms.
It may be  a one of choice I provide Anuglar/Sails/... images as third party images/stacks.

**Comment by benoitf** [comment]
I agree with @monaka that default stack (node) should contain the bare minimum while these one are 'advanced/specific'  and then cannot be in the default one

**Comment by TylerJewell** [comment]
@benoitf @eivantsov - are we ready to merge this and rebuild our images, or is there still a deeper discussion on the structure of the images required?

**Comment by eivantsov** [comment]
Image built

**Pull request merged**
