### PR TITLE
Spring Boot recipe

### PR DESCRIPTION
**Pull request by gytis**

### CODE REVIEW

**Comment by TylerJewell** [comment]
We will ask @eivantsov to review and approve.

**Comment by eivantsov** [comment]
I will build an image and push it to registry tomorrow.

**Comment by gytis** [comment]
Thanks @eivantsov

**Comment by Brad4dm** [comment]
I must be missing something  - I have Che running within Docker and I am attempting to follow the Spring Boot tutorial but I am unable to import the github spring boot app.  getting oauth issue.  I don't see how to upload my oauth cert to github nor how to download one from github.  What am I missing?

**Comment by eivantsov** [comment]
@Brad4dm can you open an issue at https://github.com/eclipse/che/issues? This is just a recipe and it has nothing to do with the way a project is imported. Try to share as many details as possible.

**Pull request merged**
