### PR TITLE
rework docker containers to be compliant with "single folder self-contained"

### PR DESCRIPTION
**Pull request by benoitf**
- each files used by Dockerfile are inside the folder
- refactor lib/typescript and lib/maven-dto to be a single docker image
- add inheritance for cheddar, che-action and che-test
- each docker entry point script is now called entrypoint.sh
- build.sh for each single directory (+ build-all.sh script at root folder to build all images)
- make sure DTO file is generated only if required ==> allow to use docker cache if no changes

Then we will be able to move these folders to eclipse/che

Change-Id: I9d77157d9232e9df9be0f363f1ba1374df6585dd
Signed-off-by: Florent BENOIT <fbenoit@codenvy.com>

### CODE REVIEW

**Comment by TylerJewell** [comment]
Ok lgtm

**Comment by benoitf** [comment]
@riuvshin let me know when you're ready as some ci-jobs may require small updates

**Comment by TylerJewell** [comment]
When we move this into the Che repo we should lose the prefixes in folders.  So it becomes IP not Che-IP.

**Comment by benoitf** [comment]
@TylerJewell yes it will be like you said

**Pull request merged**
