### PR TITLE
Install PHPUnit runtime in the PHP stack

### PR DESCRIPTION
**Pull request by kaloyan-raev**
This is complementary change in the PHP stack for https://github.com/eclipse/che/issues/3987

Signed-off-by: Kaloyan Raev <kaloyan.r@zend.com>

### CODE REVIEW

**Comment by kaloyan-raev** [comment]
I will rebase this PR once #63 is merged.

**Comment by kaloyan-raev** [comment]
@eivantsov I rebased this PR on top of the latest changes. It's ready for merge.

**Comment by kaloyan-raev** [comment]
@eivantsov This PR is merged, but it seems that the `eclipse/php` Docker image has not been rebuilt since then. Could you check?

**Comment by eivantsov** [comment]
Yes, I will rebuild and upload

**Comment by eivantsov** [comment]
Done:

image

**Pull request merged**
