### PR TITLE
Add iptables rules when running on Docker for Mac

### PR DESCRIPTION
**Pull request by l0rd**
This PR is related to eclipse/che#2402

### CODE REVIEW

**Comment by l0rd** [comment]
Some comments concerning this iptables solution:

- che-sever should run in `privileged` mode to be able use `iptables` and `sysctl` commands.  
- According to RFC 5735, network 127.0.0.0/8 should not be routed outside host itself. That's just a standard but we are ignoring it here.
- iptables is not currently installed in che-server image. It makes the image 150MB bigger.
- Users that don't use che-launcher won't benefit from this fix. They will need to run the iptables command manually.
- That's a solution for Docker for Mac only. There are other situation where che-server and the browser should use 2 distinct IPs to connect to the containers (#2030, Kubernetes and OpenShift) but that iptables approach won't be possible in such situations.
- If the ports of che-server itself are in the range 32000:65000 (that happens if che-server container is started with `-P` or if a user configure the proper environment variable with the launcher) TCP packets (correctly) directed to localhost will be redirected to the VM interface.
- If the ports exposed by the containers are not in the ephemeral port range that solution won't work anymore.
- There is no assurance that the ephemeral port range will always be 32000:65000. If in next Docker for Mac release this range is changed this solution will be broken.
- If che-server is accidentally started using --net=host the rule would be added to the xhyve VM having an impact on all the containers running there.
- It's a clever trick but not sure it will be easy for new contributors to understand and maintain.

**Comment by TylerJewell** [comment]
@garagatyi @l0rd - adding 150MB to the che-server image just to get iptables routing for rare situations is a lot.  Balloons the che-server image from 220-370MB in size.  99% of customers do not need this - so that is a huge tax to put onto the 99%.  Would we go to having two different images?  Or does the internal code change make more sense - what @l0rd originally suggested.

**Comment by l0rd** [comment]
@TylerJewell To avoid increasing the image size I've choosen to install iptables during Che start. There is no change in the che-server image size but users will have to wait a few seconds more at every che start.

**Comment by TylerJewell** [comment]
That is a good solution to that problem as long as the iptables is only installed for Mac or other configurations where this routing is explicitly required.

**Comment by l0rd** [comment]
iptables is installed on Docker for Mac only

**Comment by TylerJewell** [comment]
Let's get some solid testing on Windows & Ubuntu to go along with your changes for Mac.  I'd like to make sure the change to the `--remote` flag does not have any unintended consequences.

- [ ] QA: Docker for Windows
- [ ] QA: boot2docker Windows
- [ ] QA: Vagrant with CentOS
- [ ] QA: Ubuntu

**Comment by benoitf** [comment]
I still prefer the use of internal/external URL without the use of iptables
downloading iptable each time the che image is started is really painful It can take very long time as well
The goal of the image is that if I have it cached, I shouldn't have to download it again.

**Comment by benoitf** [comment]
@l0rd should we close this PR as https://github.com/eclipse/che/pull/2402 is an alternative ?

**Comment by l0rd** [comment]
@benoitf yes absolutely let me close it. I was waiting that eclipse/che#2402 was merged but since it has been approved I guess we can close this one.

**Pull request closed without merging**
