### PR TITLE
Chefile improvements

### PR DESCRIPTION
**Pull request by benoitf**
- [x] setup ssh keys before updating project
- [x] handle CHE_PORT environment variable
- [x] handle CHE_LAUNCHER_IMAGE_NAME
- [x] Upgrade to TypeScript 2.0
- [x] Display help when one of the argument is missing
- [x] Reduce size of the docker image by removing stuff after usage and using smaller parent image
- [x] Customize output of some commands with formatter
- [x] Add import of projects in Chefile
- [x] Export Chefile into a factory.json
- [x] Rework help sections
- [x] more unit tests

### CODE REVIEW

**Comment by TylerJewell** [comment]
@benoitf - would it make sense for us to have any sub-utilities make use of Che CLI embedded for launching other che instances?  This could simplify some behaviors - just set variables in a profile and then use the CLI to start / stop / restart instances.

**Comment by benoitf** [comment]
New Eclipse Che instances are launched with the che-launcher (docker launch) so it reuses the launcher of Eclipse Che.

AFAIK che cli embedded is a bash script while che-launcher is docker ready.
so trying to use cli shell script with profiles would require to mount USER_HOME directory or profile directory to read or write properties and also wrap sh into a docker image and it will again try to launch a new docker image ?

IMHO I don't see it being simplify there as Chefile is containing the portable definition, not the user profile

**Comment by TylerJewell** [comment]
Ok - got it.  Should be ok with the che-launcher invocation.

**Comment by TylerJewell** [comment]
Ok - just found one file that needs a newline, otherwise +1 for merge.

**Pull request merged**
