### PR TITLE
Update .NET Core SDK

### PR DESCRIPTION
**Pull request by rogersachan**
Microsoft has now pushed the stable release of .NET Core 1.1.

In this PR I have updated the following:

* Package name
* Node

Signed-off-by: Roger S <narayanroger@gmail.com>

### CODE REVIEW

**Comment by rogersachan** [comment]
I have signed off my commit @TylerJewell

**Comment by TylerJewell** [comment]
Thanks @rogersachan for the contribution.  Everything looked good and tested well.

**Comment by rogersachan** [comment]
@TylerJewell It appears that the template was never pushed to https://hub.docker.com/r/eclipse/dotnet_core/ . What happened?

**Comment by TylerJewell** [comment]
Our CI systems do not do a re-build and a push to DockerHub until there is a release (or it's manually done by one of our enginers). We have 5.5 due to be released later this week.

@eivantsov - will you consider a manual push?

**Comment by rogersachan** [comment]
@TylerJewell Do you know which repo the examples are stored in? With this release of .NET Core they have changed the project format and old projects need to be converted.

**Comment by TylerJewell** [comment]
Inside the github.com/eclipse/che repository is a file that stores all of our default stacks and templates. These are files that are preloaded into the database when Che starts.  They are just JSON.  The JSON either references a Docker image (for loading the workspace runtime) or in the case of templates, it references a git repository somewhere on the Internet.

Each stack can have many templates associated with it - and Che does a lookup / match to generate the list.

Are you looking for the git repo list for .net templates?

**Comment by rogersachan** [comment]
@TylerJewell Yes

**Comment by TylerJewell** [comment]
I think you are looking for this file.

https://github.com/eclipse/che/blob/master/ide/che-core-ide-templates/src/main/resources/samples.json

This makes the association of all templates to all stacks.

**Comment by eivantsov** [comment]
We have merged a broken recipe:

`echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main" > /etc/apt/sources.list.d/dotnetdev.list` expectedly fails due to permissions issues.

**Comment by eivantsov** [comment]
I have pushed a fix and updated image as well.

**Pull request merged**
