### PR TITLE
updated comments in che-launcher Dockerfile with correct run command

### PR DESCRIPTION
**Pull request by sbryzak**

### CODE REVIEW

**Comment by benoitf** [comment]
I would say image name will be "eclipse/che"

**Comment by TylerJewell** [comment]
@sbryzak - we are waiting for our CI systems to be updated so that all of the codenvy/* images get pushed as eclipse/* images into DockerHub.  Right now, the che-launcher is pushed as `codenvy/che-launcher` and `eclipse/che`.  But the other images in this repository are still only pushed as `codenvy/*`.  We expet the full set of images to be pushed shortly and then we need to go through all of the headers and update the usage comments.

**Comment by sbryzak** [comment]
I've added support for a property to allow specifying a docker volume to use for the ws-agent.zip:

-e "CHE_DOCKER_MACHINE_VOLUMES_LIB=che-lib-wsagent"

(see https://github.com/eclipse/che/issues/2598)

Another pull request for the Che docker plugin will be following shortly to compliment this.

**Comment by TylerJewell** [comment]
Cool!   Shayne, yesterday I setup a pr that drives a refactoring of the underlying che-server docker image to only require a single data mount instead of the three that are required today.  I then updated the Che launcher with a matching implementation to support that.  I can reference both PRs on that.  But let's figure out a way to debase your changes on top of the others so that volumes from could be used for the data mount.

**Comment by l0rd** [comment]
Shane you should do the following:
1. Keep just one commit on this PR (for the comments)
2. Rebase the second commit on top of #29 and open a second PR (on a new branch)

@TylerJewell @benoitf I think the original PR was ok. The intent was to fix the inconsistency of the image name between the build (condenvy/**che-launcher**) and the run (codenvy/**che**) command.

**Comment by sbryzak** [comment]
Hi @TylerJewell , am I right in understanding that your refactoring will make issue 2598 (https://github.com/eclipse/che/issues/2598) redundant?  If so I'll spend time working on another area, as this issue still has some problems with the implementation.  On another note, there's a typo in the script in this pull request which requires fixing, I'll do that and update the PR accordingly also taking into account Mario's suggestions.

**Comment by TylerJewell** [comment]
Hi @sbryzak - Actually, no #2598 is redundant.  We have been at a hackathon this week with @l0rd and @benoitf and @garagatyi.

We have been testing various configurations, and it seems that what we intend to do is a bit of a hybrid approach for managing agents and the project files:
1: @garagatyi is going to implement volumes-from inside of the product to manage the mounting of files for the `/projects` themselves.
2: For agent libraries, we are going to go with a hybrid approach.  If a workspace container is starting, we would like for it to first use volumes-from to check to see if the agent libraries that it needs are available locally.  However, if they are not there, we will have a workspace then download those agents from the che-master over HTTP if they are not discoverable through volumes-from.  Mario suggested that this one would be there area where you could help us out still.

The idea behind having the agents follow a hybrid approach is that having the agents downloadable from the che-server means that we can remove a dependency on agents always being loaded from a volume, which would help in distributed situations like on OpenShift.

**Comment by sbryzak** [comment]
I've removed all commits from this pull request except the one that fixes the comments inconsistency.  @TylerJewell I'm certainly happy to help out with the workspace agent transfer refactoring, I have a couple of days before I go on annual leave so if you could give me some details on what needs to be done I'll get as much implemented as possible.

**Comment by l0rd** [comment]
@benoitf @TylerJewell do you think we can merge this?

**Comment by TylerJewell** [comment]
Yeah I think we are ok.  We will have the m6 tag tomorrow and this is good to go in.

**Pull request merged**
