### PR TITLE
Updated version of .NET Core & Maintainer

### PR DESCRIPTION
**Pull request by rogersachan**
updated version via script from https://www.microsoft.com/net/core#ubuntu

I have signed the CLA

### CODE REVIEW

**Comment by rogersachan** [comment]
Why does it say it is invalid?

image

**Comment by rogersachan** [comment]
I made the edit on Github so of course it hands over a github email

**Comment by TylerJewell** [comment]
Thanks @rogersachan - I have asked the Codenvy core team to take this PR in their next sprint for QA & testing, and if no issues to merge.

**Comment by rogersachan** [comment]
I just updated the file to reflect the new keyserver and latest version.

**Pull request merged**
