### PR TITLE
Updated java images to have .m2 folder and jdtls data folder

### PR DESCRIPTION
**Pull request by JPinkney**
### What does this PR do?
Adds .m2 folder and jdtls data folder for jdtls

### What issues does this PR fix or reference?
https://github.com/eclipse/che-ls-jdt/pull/42
https://github.com/eclipse/che/pull/9616

### CODE REVIEW

**Comment by eivantsov** [comment]
@JPinkney these dirs won't be writable for OpenShift arbitrary user.

**Comment by JPinkney** [comment]
@eivantsov Do you know of a suggested way around this? Would the suggested way be to do something like [this](https://github.com/eclipse/che-dockerfiles/blob/master/recipes/stack-base/centos/Dockerfile#L45) but adding in those dirs?

**Comment by eivantsov** [comment]
Yes, make them writable for root group

**Comment by tolusha** [comment]
@eivantsov review pls.

**Comment by tolusha** [comment]
ci-test

**Comment by eivantsov** [comment]
Approved. Merge when you are ready

**Comment by benoitf** [comment]
@eivantsov FYI Josh is not yet a committer so we should merge

**Comment by tolusha** [comment]
@benoitf I have to rerun tests.

**Pull request merged**
