### PR TITLE
Added existing dockerfiles used by che.

### PR DESCRIPTION
**Pull request by JamesDrummond**
1. Copied everything from eclipse/che repo BUT /dockerfiles/Che-server folder. Removed the leading /dockerfiles folder after the move. Copied /dockerfiles/che-server/Dockerfile file to root directory.

2. Copied the contents of the codenvy/dockerfiles repo to a directory called /recipes.

### CODE REVIEW

**Comment by JamesDrummond** [comment]
@TylerJewell I removed che-server Dockerfile and add license + copy write header to files missing it.

**Comment by TylerJewell** [comment]
I am a +1 for the merge once others give a thumbs up.  This would then be our base repository for making dockerfile changes.

**Comment by TylerJewell** [comment]
@benoitf @eivantsov @riuvshin - FYI - review this new repository. This preserves our ability to release images independently of Che releases.  This takes out of the /che repo some important items that we need to release more frequently.

@JamesDrummond - we have two pull requests on the che repo that affect che-file and che-launcher.  After those pull requests are merged into che repository, then we need to bring those files over here.

After we are confident that the CI systems can work with this new repository - we can then turn off CI for the other repositories and active it here, then removing the duplicate files from the other locations.

**Comment by benoitf** [comment]
I would wait merge of https://github.com/eclipse/che/pull/2119 and https://github.com/eclipse/che/pull/2048 else this repository will be outdated

**Comment by TylerJewell** [comment]
eclipse/che#2119 has been closed, so you can grab the updated files from /che/dockerfiles/che-launcher now.

**Comment by JamesDrummond** [comment]
Updated che-launcher dockerfiles.

**Comment by benoitf** [comment]
https://github.com/eclipse/che/pull/2048 merged
and waiting for https://github.com/eclipse/che/pull/2211
after that we're good

**Comment by TylerJewell** [comment]
+1 - Jame's first pull request!

**Pull request merged**
