### PR TITLE
Node Stack Changes

### PR DESCRIPTION
**Pull request by sr229**
Changes
- Node.js Bump - Upgraded to latest LTS.

 - Image Base changed to Ubuntu - Most Developers may find it easier to work on a Ubuntu-based workspace.

- Addition of Python - some NPM Packages relies on Python.

- Addition of ESLint - I just noticed ``eslint`` isn't added and this is needed if you're working on a project and you want your code to follow the ECMAScript Guidelines.

### CODE REVIEW

**Comment by sr229** [comment]
CLA is signed btw, Still rendered that I didn't sign it though :confused:

**Comment by benoitf** [comment]
@sr229 you should amend your commits with Signed-Off
You may have signed CLA but it may not be enough as your email is not there (I think you've edited with github interface for now)
```
Signed-off-by: Your Name<email@myprovider.Com>
```

**Comment by benoitf** [comment]
> Image Base changed to Ubuntu - Most Developers may find it easier to work on a Ubuntu-based workspace.

Maybe there is a need for two images because I think most ppl don't notice if it's debian or ubuntu (debian based)

> Addition of ESLint - I just noticed eslint isn't added and this is needed if you're working on a project and you want your code to follow the ECMAScript Guidelines.

You can still also install the package but not globally if you need it for your project

**Comment by TylerJewell** [comment]
@sr229 - thanks so much for getting involved and helping us make things better here.

I'll let @eivantsov comment further, but I believe that we have made some choices that require all of our default stacks that ship with Che / Codenvy to be based upon debian or alpine for purposes of keeping stacks more consistent, smaller, and easier to manage. 

We agree that ubuntu is more friendly for development, but we have to make sure that we are consistent, and either move all default images to be from the same distribution or keep them where they are.  One of the big things that we have to work on is making it easier for people to find all of the different linux distributions for a single stack-type, like for Node.  It's a harder project, but something we need to do.

**Comment by sr229** [comment]
@TylerJewell that's nice to know, indeed Ubuntu is one of the most used for Development although if you like, I'll switch it back to Debian for the consistency.

@benoitf although you can install it on your project as your dependency, it's better for the stack to have it by default since the linting it provides also encourages to also follow NPM's good practices for coding.

**Comment by eivantsov** [comment]
We may just create another tag eclipse/node:ubuntu

**Comment by eivantsov** [comment]
I'm closing this PR. Node version has been updated in eclipse/node image - https://github.com/eclipse/che-dockerfiles/blob/master/recipes/node/Dockerfile#L10

If you need the same stack based on debian, please open a different pr

**Pull request closed without merging**
