### PR TITLE
Add Theia image

### PR DESCRIPTION
**Pull request by eivantsov**
### What does this PR do?
This PR add recipe and build script for an image with Theia that has yarn cache and pre-built Theia with a limited number of plugins.

### CODE REVIEW

**Comment by benoitf** [comment]
what is difference with https://github.com/eclipse/che/tree/master/dockerfiles/theia ?

**Comment by eivantsov** [comment]
1. No ssh plugin
2. Fixed versions in full package.json
3. Script that checks package availability and replaces latest with a fixed version.

Dockerfile from Che repo will be removed. We will use this one, and tag with with Theia release, not Che.

**Comment by benoitf** [comment]
where is it being discussed ?

**Comment by eivantsov** [comment]
I haven't made a PR to Che repo yet.

This PR in dockerfiles fixes  https://github.com/eclipse/che/issues/9649

**Comment by benoitf** [comment]
I mean, where has it been discussed that it will be moved from che repo to che-dockerfiles repo ?

**Comment by eivantsov** [comment]
I have just issued a PR to Che repo.

**Comment by riuvshin** [comment]
should be closed?

**Comment by eivantsov** [comment]
Yes. Closing

**Pull request closed without merging**
