### PR TITLE
CHE-2059 Add workspace-ssh command that connect to remote workspaces

### PR DESCRIPTION
**Pull request by benoitf**
Change-Id: Ic30f26592fa8cf002fbdc9a23c748062be7d18e0
Signed-off-by: Florent BENOIT <fbenoit@codenvy.com>

### CODE REVIEW

**Comment by benoitf** [comment]
@TylerJewell for review

**Comment by benoitf** [comment]
how to use it:
```
$ che action workspace-ssh :workspaceName
$ che action workspace-ssh workspaceId
```

**Comment by benoitf** [comment]
on macos :

with che
```
docker run --cap-add SYS_ADMIN --device /dev/fuse -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/mnthost -ti codenvy/che-mount:nightly <workspace-name>
```


with remote server (that has workspace ssh keys enabled):
```
docker run --cap-add SYS_ADMIN --device /dev/fuse -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/mnthost -ti codenvy/che-mount:nightly <workspace-name> --url=https://<myserver> --user=<my-email> --password <my-password>
```

**Comment by benoitf** [comment]
@TylerJewell

**Comment by TylerJewell** [comment]
+1 - looks good.

**Pull request merged**
