### PR TITLE
Bash completion

### LINKED ISSUE #61: Bash completion
Currently the Terminal in Che provides only basic auto completion, like:

```sh
gi[TAB]
```

But it does not provide auto completion for command's arguments (except for those which a file paths) like:
```sh
git sta[TAB]
```

The latter is usually available on the Linux desktop and I am really missing it in the Che Terminal.

To achive auto completion for command arguments the base Che Docker images must be updated in the following way:

1. Install the `bash-completion` package:

```sh
sudo apt-get install bash-completion
```

2. Activate the bash completion when the Terminal is started by adding the following to `/etc/profile`:

```sh
if [ -f /etc/bash_completion ]; then
 . /etc/bash_completion
fi
```

### PR DESCRIPTION
**Pull request by kaloyan-raev**
Fixes #61 

This PR installs the bash-completion package in the stack-base images: both Debian and Ubuntu. It also installs the Composer-specific bash completion in the PHP stack.

### CODE REVIEW

**Comment by kaloyan-raev** [comment]
@eivantsov do you think this can be merged?

**Comment by eivantsov** [comment]
@kaloyan-raev yes!

**Comment by eivantsov** [comment]
Done. Images updated and pushed. Bash completions is now available in all Che stacks.

**Comment by kaloyan-raev** [comment]
Thanks!

**Pull request merged**
